spring:
  application:
    name: wellknown-service
server:
  port: 8086

idp:
  openid:
    issuer: http://localhost:8080/wellknown
    jwksUri: http://localhost:8080/wellknown/jwks

    authorizationEndpoint: http://localhost:8080/oauth2/authorize
    tokenEndpoint: http://localhost:8080/oauth2/token
    userInfoEndpoint: http://localhost:8080/oauth2/userinfo
    introspectionEndpoint: http://localhost:8080/oauth2/introspect
    revocationEndpoint: http://localhost:8080/oauth2/revoke
    endSessionEndpoint: http://localhost:8080/logout

    responseTypesSupported: [ "code", "id_token", "token id_token" ]
    subjectTypesSupported: [ "public" ]
    grantTypesSupported: [ "authorization_code", "refresh_token", "client_credentials" ]
    tokenEndpointAuthMethodsSupported: [ "client_secret_basic", "client_secret_post" ]

    scopesSupported: [ "openid", "profile", "email", "offline_access" ]
    claimsSupported: [ "sub", "email", "name", "preferred_username" ]

    idTokenSigningAlgValuesSupported: [ "RS256" ]

jwks:
  cache-key: JWKS
  cache-ttl-millis: 600000 # 10 minutes
